<a href="https://colab.research.google.com/github/kabranov/vidin/blob/master/MG_Vidin_2019_RestaurantSentimentAnalysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


reference
https://www.kaggle.com/apekshakom/sentiment-analysis-of-restaurant-reviews

https://www.geeksforgeeks.org/python-nlp-analysis-of-restaurant-reviews/




#Анализ на сентименти на ревюта за ресторанти

Целта на този анализ е да се създаде предиктивен модел да се предскаже дали сентимента на коментар на ресторант е позитивен или негативен. За обучение на модела ще използваме логистична регресия. 

Dataset: https://www.kaggle.com/hj5992/restaurantreviews
 
 
Базата от данни е от Kaggle datasets - 1000 ревюта на ресторанти.

необходимо да направим следните стъпки:
- да се импортира базата от данни 
- да се извърши предварителна обработка
- векторизация
- Обучение и класификация
- Анализ и заключние




# да се импортира базата от данни

> Indented block


Импорт на базата данни, използвайки pandas библиотека.


In [1]:
# Importing the libraries
import numpy as np
import pandas as pd

In [ ]:
# Importing the datas
from google.colab import drive
drive.mount('/content/drive')
# That will not be needed if it executed on a local drive.

import os
cwd = os.getcwd()
print(cwd)
print(os.listdir() )
dataset = pd.read_csv('/content/drive/My Drive/Restaurant_Reviews.tsv', delimiter = '\t', quoting = 3)

!ls -l

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&response_type=code&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly

Enter your authorization code:
··········
Mounted at /content/drive
/content
['.config', 'drive', 'sample_data']
total 8
drwx------ 4 root root 4096 Mar 12 05:56 drive
drwxr-xr-x 1 root root 4096 Mar  3 18:11 sample_data


In [ ]:
print("size=%d",dataset.size)
dataset.head(30)

size=%d 2000


Review  Liked
0                            Wow... Loved this place.      1
1                                  Crust is not good.      0
2           Not tasty and the texture was just nasty.      0
3   Stopped by during the late May bank holiday of...      1
4   The selection on the menu was great and so wer...      1
5      Now I am getting angry and I want my damn pho.      0
6               Honeslty it didn't taste THAT fresh.)      0
7   The potatoes were like rubber and you could te...      0
8                           The fries were great too.      1
9                                      A great touch.      1
10                           Service was very prompt.      1
11                                 Would not go back.      0
12  The cashier had no care what so ever on what I...      0
13  I tried the Cape Cod ravoli, chicken, with cra...      1
14  I was disgusted because I was pretty sure that...      0
15  I was shocked because no signs indicate cash o...      0
16                                Highly recommended.      1
17             Waitress was a little slow in service.      0
18  This place is not worth your time, let alone V...      0
19                               did not like at all.      0
20                                The Burrittos Blah!      0
21                                 The food, amazing.      1
22                              Service is also cute.      1
23  I could care less... The interior is just beau...      1
24                                 So they performed.      1
25  That's right....the red velvet cake.....ohhh t...      1
26         - They never brought a salad we asked for.      0
27  This hole in the wall has great Mexican street...      1
28  Took an hour to get our food only 4 tables in ...      0
29                  The worst was the salmon sashimi.      0

#Предварителна обработка

Всяко ревю се подлага на предварителна обработка, където:

- премахват се stopwords, numeric и speacial charecters.
- извирвършва се stemming.

![alt text](https://media.geeksforgeeks.org/wp-content/uploads/stemming.png)

използва се само корена на думата.

In [ ]:
# library to clean data 
import re
# Natural Language Tool Kit 
import nltk
# for Stemming propose 
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
# Initialize empty array 
# to append clean text  
corpus = []
nltk.download('stopwords')
# 1000 (reviews) rows to clean 
for i in range(0, 1000):
    # column : "Review", row ith 
    review = re.sub('[^a-zA-Z]', ' ', dataset['Review'][i])
    # convert all cases to lower cases 
    review = review.lower()
    # split to array(default delimiter is " ")
    review = review.split()
    # creating PorterStemmer object to 
    # take main stem of each word 
    ps = PorterStemmer()
    review = [ps.stem(word) for word in review if not word in set(stopwords.words('english'))]
    # rejoin all string array elements 
    # to create back into a string 
    review = ' '.join(review)
          
    # append each string to create 
    # array of clean text
    corpus.append(review)

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


In [ ]:
print( dataset)
print("---")
for i in range(0,10):
  print( dataset['Review'][i],"--->", dataset['Liked'][i])
  print("==> stemmed : " , corpus[i])

                                                Review  Liked
0                             Wow... Loved this place.      1
1                                   Crust is not good.      0
2            Not tasty and the texture was just nasty.      0
3    Stopped by during the late May bank holiday of...      1
4    The selection on the menu was great and so wer...      1
..                                                 ...    ...
995  I think food should have flavor and texture an...      0
996                           Appetite instantly gone.      0
997  Overall I was not impressed and would not go b...      0
998  The whole experience was underwhelming, and I ...      0
999  Then, as if I hadn't wasted enough of my life ...      0

[1000 rows x 2 columns]
---
Wow... Loved this place. ---> 1
==> stemmed :  wow love place
Crust is not good. ---> 0
==> stemmed :  crust good
Not tasty and the texture was just nasty. ---> 0
==> stemmed :  tasti textur nasti
Stopped by during the late May

#Векторизация


От изчистения набор от данни се извличат думите и се преобразуват във векторизиран формат. Техниките за векторизация се използват за преобразуване на текстови данни в цифров формат. С помощта на векторизация се създава матрица, където всяка колона представлява функция и всеки ред представлява индивидуално ревю.


Input : 
* "dam good steak", 
* "good food good servic"

Output :

![alt text](https://media.geeksforgeeks.org/wp-content/uploads/eg.png)

In [ ]:
# Creating the Bag of Words model using CountVectorizer
from sklearn.feature_extraction.text import CountVectorizer
# To extract max 1500 feature. 
# "max_features" is attribute to 
# experiment with to get better results 

cv = CountVectorizer(max_features = 1500)

# X contains corpus (dependent variable) 
X = cv.fit_transform(corpus).toarray()

# y contains answers if review 
# is positive or negative 
y = dataset.iloc[:, 1].values

In [ ]:
#dataset.iloc[:, 1]

In [ ]:
#dataset.iloc[:, 0]

In [ ]:
print(X)
print(len(X[0]))
print(X[0][10])

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
1500
0


# Обучение и класификация
о-нататък данните се разделят на набор за обучение и тестване. Тези данни се използват като вход към алгоритъма за класификация.
За предиктивен модел се изполсва логистична класификация

In [ ]:
# Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state = 42)

In [ ]:
# Logistic Regression

# Fitting Logistic Regression to the Training set
from sklearn import linear_model
classifier = linear_model.LogisticRegression(C=1.5)
classifier.fit(X_train, y_train)

# Predicting the Test set results
y_pred = classifier.predict(X_test)


# Accuracy
from sklearn.metrics import accuracy_score
score1 = accuracy_score(y_test,y_pred)
print("\n")
print("Accuracy is ",round(score1*100,2),"%")



Accuracy is  76.67 %


In [ ]:
print(cv.get_feature_names())

['absolut', 'absolutley', 'accid', 'accommod', 'accomod', 'accordingli', 'account', 'ach', 'acknowledg', 'across', 'actual', 'ad', 'afford', 'afternoon', 'ago', 'ahead', 'airlin', 'airport', 'ala', 'albondiga', 'allergi', 'almond', 'almost', 'alon', 'also', 'although', 'alway', 'amaz', 'ambianc', 'ambienc', 'amount', 'ampl', 'andddd', 'angri', 'annoy', 'anoth', 'anticip', 'anymor', 'anyon', 'anyth', 'anytim', 'anyway', 'apart', 'apolog', 'app', 'appal', 'appar', 'appeal', 'appet', 'appetit', 'appl', 'approv', 'area', 'arepa', 'aria', 'around', 'array', 'arriv', 'articl', 'ask', 'assur', 'ate', 'atmospher', 'atroci', 'attach', 'attack', 'attent', 'attitud', 'auju', 'authent', 'averag', 'avocado', 'avoid', 'aw', 'away', 'awesom', 'awkward', 'awkwardli', 'ayc', 'az', 'baba', 'babi', 'bachi', 'back', 'bacon', 'bad', 'bagel', 'bakeri', 'baklava', 'ball', 'bamboo', 'banana', 'bank', 'bar', 'bare', 'bargain', 'bartend', 'base', 'basebal', 'basic', 'batch', 'bathroom', 'batter', 'bay', 'bbq', 

In [ ]:
sentiments = []
sentiments.append("this restaurant sucks, really bad")
sentiments.append("great place great food")
sentiments.append("food tasted good. I will visit again")
sentiments.append("just horrible. I will never set foot again")
sentiments.append("My wife finds the food very good.")
sentiments.append("Just two words: unpleasant and dirty.")
sentiments.append("Clean, friendly, good food")

vectorized_sentiments = cv.transform(sentiments).toarray()

In [ ]:
y_pred = classifier.predict(vectorized_sentiments)

In [ ]:
print(y_pred)

[0 1 1 0 1 0 1]
